config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :pics do
    member do
      put 'like',to:'pics#upvote'
    end
  end

  root 'pics#index'

end

app/models/pic.rb
# == Schema Information
#
# Table name: pics
#
#  id                 :integer          not null, primary key
#  title              :string(255)
#  description        :text(65535)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  user_id            :integer
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Pic < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController


  before_action :find_pic, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pics=Pic.all.order("created_at DESC")
  end

  def show
  end

  def new
    # pictures are being built by current user
    @pic=current_user.pics.build
  end

  def create
    @pic=current_user.pics.build(picParams)
    if @pic.save
      redirect_to pic_path(@pic), notice: "Yess! It was posted."
    else
      render 'new'
    end
  end

  def edit
  end

  def update

    if @pic.update(picParams)
      redirect_to pic_path(@pic), notice: "Congrats! your pic has been updated."
    else
      render 'edit'
    end
  end

  def destroy
    @pic.destroy
    redirect_to root_path
  end

  def upvote
    @pic.upvote_by current_user
    redirect_to :back
  end

  private
  def picParams
    params.require(:pic).permit(:title, :description, :image)
  end

  def find_pic
    @pic =Pic.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagraaamy</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 70px;">

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-brand">
      <%= link_to 'Instagraaam', root_path %>
    </div>
    <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Gram It! ', new_pic_path %></li>
          <li><%= link_to 'Settings ', edit_user_registration_path %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
        </ul>
    <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Join Us ', new_user_registration_path %></li>
          <li><%= link_to 'Login', new_user_session_path %></li>
        </ul>
    <% end %>


  </div>
</nav>

<div>
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/pics/_form.html.erb
<div class="container-fluid">
  <%= simple_form_for @pic, :html => {multipart: true} do |f| %>
      <% if @pic.errors.any? %>
          <div class="errors">
            <h2><%= pluralize @pic.errors.count, "error" %> prevented this pic from saving</h2>
            <ul>
              <% @pic.errors.full_message.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= f.input :title, input_html: {class: 'form-control'} %>
        <%= f.input :image, as: :file,input_html: {class: 'form-control'} %>
        <%= f.input :description, input_html: {class: 'form-control'} %>
        <%= f.button :button, class: "btn  btn-info" %>
      </div>
  <% end %>
</div>

app/views/pics/edit.html.erb
<div class="container-fluid">
  <div class="col-md-8 col-offset-2" id="edit_page">

    <div class="row">
      <div class="panel panel-default">
        <div class="panel-heading">

          <h1>Edit Pic</h1>
        </div>
        <div class="panel-body">
          <div id="current_image">
            <strong class="center">
              Right Now
            </strong>
            <br>
            <%= image_tag @pic.image.url(:medium) %>

          </div>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pics/index.html.erb
<div class="col-md-12 ">
  <div id="pics" class="transistion-enabled">
    <% @pics.each do |pic| %>
        <div class="box panel panel-default">
          <%= link_to (image_tag pic.image.url), pic_path(pic) %>
          <h2><%= link_to pic.title, pic_path(pic) %></h2>
        </div>

    <% end %>

  </div>
</div>

app/views/pics/new.html.erb
<div class="container-fluid">
  <div class="col-md-8 col-offset-2">
    <div class="row">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1>Post Pic</h1>
        </div>
        <div class="panel-body">
          <%= render 'form' %>

        </div>
      </div>
    </div>
  </div>

</div>

app/views/pics/show.html.erb
<div class="container-fluid">
  <div id="pic_show" class="row">
    <div class="col-md-6 col-md-offset-3 col-ld-6 col-ld-offset-3">
      <div class="panel panel-default">
        <div class="panel heading pic_image"><%= image_tag @pic.image %></div>
        <div class="panel-body">
          <h1><%= @pic.title %></h1>


          <p><%= @pic.description %></p>


        </div>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-6">
              <p>Pic By : <%= @pic.user.email %></p>
            </div>
            <div class="col-md-6">
              <div class="btn-group pull-right ">
                <%= link_to like_pic_path(@pic), method: :put, class: "btn btn-default" do %>
                    <span class="glyphicon glyphicon-thumbs-up"><%= @pic.get_upvotes.size %></span>
                <% end %>

                <% if user_signed_in? %>
                    <%= link_to 'Edit', edit_pic_path, class: "btn btn-info" %>
                    <%= link_to 'Delete', pic_path, class: "btn btn-danger", :method => :delete, data: {confirm: "Are you sure"} %>
                <% end %>
              </div>
            </div>

          </div>
        </div>

      </div>
    </div>

  </div>


</div>